/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRequestsRouteImport } from './routes/contact-requests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as ContentSolutionsRouteImport } from './routes/content/solutions'
import { Route as ContentSettingsRouteImport } from './routes/content/settings'
import { Route as ContentLoginRouteImport } from './routes/content/login'
import { Route as ContentLearnRouteImport } from './routes/content/learn'
import { Route as ContentJsonRouteImport } from './routes/content/json'
import { Route as ContentInnovationRouteImport } from './routes/content/innovation'
import { Route as ContentImpactInsightsRouteImport } from './routes/content/impact-insights'
import { Route as ContentHomeRouteImport } from './routes/content/home'
import { Route as ContentHistoryRouteImport } from './routes/content/history'
import { Route as ContentGameRouteImport } from './routes/content/game'
import { Route as ContentContactRouteImport } from './routes/content/contact'
import { Route as ContentCareersRouteImport } from './routes/content/careers'
import { Route as ContentAboutRouteImport } from './routes/content/about'

const ContactRequestsRoute = ContactRequestsRouteImport.update({
  id: '/contact-requests',
  path: '/contact-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSolutionsRoute = ContentSolutionsRouteImport.update({
  id: '/content/solutions',
  path: '/content/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSettingsRoute = ContentSettingsRouteImport.update({
  id: '/content/settings',
  path: '/content/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentLoginRoute = ContentLoginRouteImport.update({
  id: '/content/login',
  path: '/content/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentLearnRoute = ContentLearnRouteImport.update({
  id: '/content/learn',
  path: '/content/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentJsonRoute = ContentJsonRouteImport.update({
  id: '/content/json',
  path: '/content/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentInnovationRoute = ContentInnovationRouteImport.update({
  id: '/content/innovation',
  path: '/content/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentImpactInsightsRoute = ContentImpactInsightsRouteImport.update({
  id: '/content/impact-insights',
  path: '/content/impact-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentHomeRoute = ContentHomeRouteImport.update({
  id: '/content/home',
  path: '/content/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentHistoryRoute = ContentHistoryRouteImport.update({
  id: '/content/history',
  path: '/content/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentGameRoute = ContentGameRouteImport.update({
  id: '/content/game',
  path: '/content/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContactRoute = ContentContactRouteImport.update({
  id: '/content/contact',
  path: '/content/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCareersRoute = ContentCareersRouteImport.update({
  id: '/content/careers',
  path: '/content/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentAboutRoute = ContentAboutRouteImport.update({
  id: '/content/about',
  path: '/content/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-requests': typeof ContactRequestsRoute
  '/content/about': typeof ContentAboutRoute
  '/content/careers': typeof ContentCareersRoute
  '/content/contact': typeof ContentContactRoute
  '/content/game': typeof ContentGameRoute
  '/content/history': typeof ContentHistoryRoute
  '/content/home': typeof ContentHomeRoute
  '/content/impact-insights': typeof ContentImpactInsightsRoute
  '/content/innovation': typeof ContentInnovationRoute
  '/content/json': typeof ContentJsonRoute
  '/content/learn': typeof ContentLearnRoute
  '/content/login': typeof ContentLoginRoute
  '/content/settings': typeof ContentSettingsRoute
  '/content/solutions': typeof ContentSolutionsRoute
  '/content/': typeof ContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-requests': typeof ContactRequestsRoute
  '/content/about': typeof ContentAboutRoute
  '/content/careers': typeof ContentCareersRoute
  '/content/contact': typeof ContentContactRoute
  '/content/game': typeof ContentGameRoute
  '/content/history': typeof ContentHistoryRoute
  '/content/home': typeof ContentHomeRoute
  '/content/impact-insights': typeof ContentImpactInsightsRoute
  '/content/innovation': typeof ContentInnovationRoute
  '/content/json': typeof ContentJsonRoute
  '/content/learn': typeof ContentLearnRoute
  '/content/login': typeof ContentLoginRoute
  '/content/settings': typeof ContentSettingsRoute
  '/content/solutions': typeof ContentSolutionsRoute
  '/content': typeof ContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-requests': typeof ContactRequestsRoute
  '/content/about': typeof ContentAboutRoute
  '/content/careers': typeof ContentCareersRoute
  '/content/contact': typeof ContentContactRoute
  '/content/game': typeof ContentGameRoute
  '/content/history': typeof ContentHistoryRoute
  '/content/home': typeof ContentHomeRoute
  '/content/impact-insights': typeof ContentImpactInsightsRoute
  '/content/innovation': typeof ContentInnovationRoute
  '/content/json': typeof ContentJsonRoute
  '/content/learn': typeof ContentLearnRoute
  '/content/login': typeof ContentLoginRoute
  '/content/settings': typeof ContentSettingsRoute
  '/content/solutions': typeof ContentSolutionsRoute
  '/content/': typeof ContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-requests'
    | '/content/about'
    | '/content/careers'
    | '/content/contact'
    | '/content/game'
    | '/content/history'
    | '/content/home'
    | '/content/impact-insights'
    | '/content/innovation'
    | '/content/json'
    | '/content/learn'
    | '/content/login'
    | '/content/settings'
    | '/content/solutions'
    | '/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-requests'
    | '/content/about'
    | '/content/careers'
    | '/content/contact'
    | '/content/game'
    | '/content/history'
    | '/content/home'
    | '/content/impact-insights'
    | '/content/innovation'
    | '/content/json'
    | '/content/learn'
    | '/content/login'
    | '/content/settings'
    | '/content/solutions'
    | '/content'
  id:
    | '__root__'
    | '/'
    | '/contact-requests'
    | '/content/about'
    | '/content/careers'
    | '/content/contact'
    | '/content/game'
    | '/content/history'
    | '/content/home'
    | '/content/impact-insights'
    | '/content/innovation'
    | '/content/json'
    | '/content/learn'
    | '/content/login'
    | '/content/settings'
    | '/content/solutions'
    | '/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRequestsRoute: typeof ContactRequestsRoute
  ContentAboutRoute: typeof ContentAboutRoute
  ContentCareersRoute: typeof ContentCareersRoute
  ContentContactRoute: typeof ContentContactRoute
  ContentGameRoute: typeof ContentGameRoute
  ContentHistoryRoute: typeof ContentHistoryRoute
  ContentHomeRoute: typeof ContentHomeRoute
  ContentImpactInsightsRoute: typeof ContentImpactInsightsRoute
  ContentInnovationRoute: typeof ContentInnovationRoute
  ContentJsonRoute: typeof ContentJsonRoute
  ContentLearnRoute: typeof ContentLearnRoute
  ContentLoginRoute: typeof ContentLoginRoute
  ContentSettingsRoute: typeof ContentSettingsRoute
  ContentSolutionsRoute: typeof ContentSolutionsRoute
  ContentIndexRoute: typeof ContentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact-requests': {
      id: '/contact-requests'
      path: '/contact-requests'
      fullPath: '/contact-requests'
      preLoaderRoute: typeof ContactRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/solutions': {
      id: '/content/solutions'
      path: '/content/solutions'
      fullPath: '/content/solutions'
      preLoaderRoute: typeof ContentSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/settings': {
      id: '/content/settings'
      path: '/content/settings'
      fullPath: '/content/settings'
      preLoaderRoute: typeof ContentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/login': {
      id: '/content/login'
      path: '/content/login'
      fullPath: '/content/login'
      preLoaderRoute: typeof ContentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/learn': {
      id: '/content/learn'
      path: '/content/learn'
      fullPath: '/content/learn'
      preLoaderRoute: typeof ContentLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/json': {
      id: '/content/json'
      path: '/content/json'
      fullPath: '/content/json'
      preLoaderRoute: typeof ContentJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/innovation': {
      id: '/content/innovation'
      path: '/content/innovation'
      fullPath: '/content/innovation'
      preLoaderRoute: typeof ContentInnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/impact-insights': {
      id: '/content/impact-insights'
      path: '/content/impact-insights'
      fullPath: '/content/impact-insights'
      preLoaderRoute: typeof ContentImpactInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/home': {
      id: '/content/home'
      path: '/content/home'
      fullPath: '/content/home'
      preLoaderRoute: typeof ContentHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/history': {
      id: '/content/history'
      path: '/content/history'
      fullPath: '/content/history'
      preLoaderRoute: typeof ContentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/game': {
      id: '/content/game'
      path: '/content/game'
      fullPath: '/content/game'
      preLoaderRoute: typeof ContentGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/contact': {
      id: '/content/contact'
      path: '/content/contact'
      fullPath: '/content/contact'
      preLoaderRoute: typeof ContentContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/careers': {
      id: '/content/careers'
      path: '/content/careers'
      fullPath: '/content/careers'
      preLoaderRoute: typeof ContentCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/about': {
      id: '/content/about'
      path: '/content/about'
      fullPath: '/content/about'
      preLoaderRoute: typeof ContentAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRequestsRoute: ContactRequestsRoute,
  ContentAboutRoute: ContentAboutRoute,
  ContentCareersRoute: ContentCareersRoute,
  ContentContactRoute: ContentContactRoute,
  ContentGameRoute: ContentGameRoute,
  ContentHistoryRoute: ContentHistoryRoute,
  ContentHomeRoute: ContentHomeRoute,
  ContentImpactInsightsRoute: ContentImpactInsightsRoute,
  ContentInnovationRoute: ContentInnovationRoute,
  ContentJsonRoute: ContentJsonRoute,
  ContentLearnRoute: ContentLearnRoute,
  ContentLoginRoute: ContentLoginRoute,
  ContentSettingsRoute: ContentSettingsRoute,
  ContentSolutionsRoute: ContentSolutionsRoute,
  ContentIndexRoute: ContentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
